

#ifndef GRAPHICSCONSTANTS_H
#define GRAPHICSCONSTANTS_H

#define AMBIENT_SETTING 1
#define DIFFUSE_SETTING 2
#define SPECULAR_SETTING 4
#define ONLY_CONTOUR_SETTING 8

#define OMNI_LIGHTS_AMOUNT 10
#define AMBIENT_STRENGTH 0.18f
#define DIFFUSE_STRENGTH 0.80f
#define SPECULAR_STRENGTH 3.80f

#endif
